spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost
    port: 9090
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 2000ms # 连接超时时间（毫秒）
    password: # Redis服务器连接密码（默认为空）
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .htm

server:
  tomcat:
    uri-encoding: utf-8


wx:
  token: liuduxinhan
  app:
    id: wx1b7098758fffeb14
    secret: 2c0a83d6538e7f2e791843753dcdd426

baidu:
  app:
    id: 20257120
    key: 44gBVENUaNk6RTZZt34Ke2yy
    secret: X4oL7BQzxwWG8izGWfK986n2QQBZRLVP
